### ISSUE TITLE
Motivation

### ISSUE THREAD

**Issue by ZhouCX117** [FupingWu90/MERU#1]
Thanks for your excellent work and for sharing the code. I am reading the literature about semi-supervised recently. This is the first paper I read from the perspective of risk minimization, so I am a little confused. What is the key to this method? Is class-wise expected risk for unlabeled data?

**Comment by FupingWu90** [comment]
> 

Thanks. Yes, the key is to estimate the class-wise expected risk for unlabeled data, and a suitable estimator for it/them.
